mysql:
  hostname: 127.0.0.1
  username: root
  password: "password"
  database: "database"
  table: "table"
  port: 3306
  options: "?useSSL=false"
plugin:
  server: "Server Name"
  joinmsg: "JoinPlayer"
  quitmsg: "QuitPlayer"